# Generated by Django 4.2.7 on 2023-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calorie",
            name="calories",
            field=models.FloatField(null=True),
        ),
    ]
